import { DashboardData } from "../types";

export const mockDashboardData: DashboardData = {
  user: {
    id: "1",
    email: "user@example.com",
    name: "John Doe",
    phone: "+966501234567",
    role: "individual",
    userType: "personal",
    status: "active",
    avatar: "/avatar.png",
    isVerified: true,
    registrationDate: "2024-01-15T00:00:00Z",
    lastLogin: "2024-12-07T10:30:00Z",
  },
  kpis: [
    {
      id: "total-projects",
      label: "Total Projects",
      value: 12,
      previousValue: 10,
      change: 2,
      changeType: "increase",
      format: "number",
      icon: "FolderOpen",
      color: "blue",
    },
    {
      id: "active-projects",
      label: "Active Projects",
      value: 3,
      previousValue: 4,
      change: -1,
      changeType: "decrease",
      format: "number",
      icon: "Clock",
      color: "orange",
    },
    {
      id: "completed-projects",
      label: "Completed",
      value: 8,
      previousValue: 6,
      change: 2,
      changeType: "increase",
      format: "number",
      icon: "CheckCircle",
      color: "green",
    },
    {
      id: "total-spent",
      label: "Total Spent",
      value: 75000,
      previousValue: 65000,
      change: 10000,
      changeType: "increase",
      format: "currency",
      icon: "DollarSign",
      color: "purple",
    },
  ],
  recentProjects: [
    {
      id: "proj-1",
      title: "Villa Construction in Riyadh",
      description: "Modern 3-bedroom villa with contemporary design",
      status: "in_progress",
      category: "construction",
      location: "Riyadh, Saudi Arabia",
      budget: {
        min: 800000,
        max: 1200000,
        currency: "SAR",
      },
      timeline: {
        startDate: "2024-11-01T00:00:00Z",
        endDate: "2025-03-01T00:00:00Z",
        duration: 120,
      },
      requiredSkills: ["construction", "project-management", "architecture"],
      clientId: "1",
      clientName: "Ahmed Al-Rashid",
      createdAt: "2024-10-15T00:00:00Z",
      updatedAt: "2024-12-07T00:00:00Z",
      isUrgent: false,
      progress: {
        percentage: 45,
        currentPhase: "Foundation Work",
        completedTasks: 12,
        totalTasks: 28,
        milestones: [
          {
            id: "ms1",
            title: "Foundation Complete",
            description: "Complete foundation and ground work",
            dueDate: "2024-12-15T00:00:00Z",
            status: "in_progress",
          },
        ],
      },
    },
    {
      id: "proj-2",
      title: "Office Building Renovation",
      description: "Complete renovation of 5-floor office building",
      status: "completed",
      category: "construction",
      location: "Jeddah, Saudi Arabia",
      budget: {
        min: 500000,
        max: 750000,
        currency: "SAR",
      },
      timeline: {
        startDate: "2024-08-01T00:00:00Z",
        endDate: "2024-11-30T00:00:00Z",
        duration: 120,
      },
      requiredSkills: ["renovation", "interior-design", "electrical"],
      clientId: "2",
      clientName: "Sara Mohamed",
      createdAt: "2024-07-15T00:00:00Z",
      updatedAt: "2024-11-30T00:00:00Z",
      isUrgent: false,
      progress: {
        percentage: 100,
        currentPhase: "Completed",
        completedTasks: 25,
        totalTasks: 25,
        milestones: [],
      },
    },
  ],
  recentOffers: [
    {
      id: "offer-1",
      projectId: "proj-3",
      projectTitle: "Apartment Complex Design",
      contractorId: "cont-1",
      contractorName: "Modern Construction Co.",
      contractorRating: 4.8,
      status: "pending",
      amount: 950000,
      currency: "SAR",
      timeline: {
        estimatedDuration: 90,
        proposedStartDate: "2025-01-15T00:00:00Z",
        proposedEndDate: "2025-04-15T00:00:00Z",
      },
      description:
        "Complete construction of 24-unit apartment complex with modern amenities",
      submittedAt: "2024-12-05T00:00:00Z",
      updatedAt: "2024-12-05T00:00:00Z",
      isCounterOffer: false,
    },
  ],
  notifications: [
    {
      id: "notif-1",
      userId: "1",
      type: "offer_received",
      title: "New Offer Received",
      message:
        "You have received a new offer for your Villa Construction project",
      priority: "high",
      isRead: false,
      createdAt: "2024-12-07T09:30:00Z",
      actionUrl: "/dashboard/offers/offer-1",
      actionLabel: "View Offer",
    },
    {
      id: "notif-2",
      userId: "1",
      type: "milestone_completed",
      title: "Milestone Completed",
      message:
        "Foundation work has been completed for Villa Construction project",
      priority: "medium",
      isRead: false,
      createdAt: "2024-12-06T16:45:00Z",
      actionUrl: "/dashboard/projects/proj-1",
      actionLabel: "View Project",
    },
    {
      id: "notif-3",
      userId: "1",
      type: "payment_due",
      title: "Payment Due",
      message: "Payment of SAR 150,000 is due for Office Building Renovation",
      priority: "urgent",
      isRead: true,
      createdAt: "2024-12-05T08:00:00Z",
      readAt: "2024-12-05T09:15:00Z",
      actionUrl: "/dashboard/payments",
      actionLabel: "Make Payment",
    },
  ],
  quickActions: [
    {
      id: "new-project",
      label: "Post New Project",
      description: "Create a new project and find contractors",
      icon: "Plus",
      url: "/dashboard/projects/new",
      color: "blue",
      isEnabled: true,
      requiresVerification: false,
    },
    {
      id: "view-offers",
      label: "View Offers",
      description: "Review and manage project offers",
      icon: "FileText",
      url: "/dashboard/offers",
      color: "green",
      isEnabled: true,
      requiresVerification: false,
    },
    {
      id: "messages",
      label: "Messages",
      description: "Chat with contractors and suppliers",
      icon: "MessageCircle",
      url: "/dashboard/messages",
      color: "purple",
      isEnabled: true,
      requiresVerification: false,
    },
    {
      id: "payments",
      label: "Payments",
      description: "Manage payments and invoices",
      icon: "CreditCard",
      url: "/dashboard/payments",
      color: "orange",
      isEnabled: true,
      requiresVerification: true,
    },
  ],
  announcements: [
    {
      id: "announce-1",
      title: "Platform Update",
      content:
        "New features have been added to improve your project management experience",
      type: "info",
      priority: "medium",
      isActive: true,
      createdAt: "2024-12-01T00:00:00Z",
      targetRoles: ["individual", "contractor"],
    },
    {
      id: "announce-2",
      title: "Holiday Notice",
      content:
        "Customer support will have limited availability during the holiday season",
      type: "warning",
      priority: "low",
      isActive: true,
      expiresAt: "2025-01-05T00:00:00Z",
      createdAt: "2024-12-15T00:00:00Z",
    },
  ],
  calendar: [
    {
      id: "cal-1",
      title: "Foundation Inspection",
      description: "Final inspection of foundation work",
      startDate: "2024-12-15T10:00:00Z",
      endDate: "2024-12-15T12:00:00Z",
      type: "milestone",
      status: "upcoming",
      relatedEntityId: "proj-1",
      relatedEntityType: "project",
    },
    {
      id: "cal-2",
      title: "Contractor Meeting",
      description: "Weekly progress meeting with construction team",
      startDate: "2024-12-10T14:00:00Z",
      endDate: "2024-12-10T15:00:00Z",
      type: "meeting",
      status: "upcoming",
      relatedEntityId: "proj-1",
      relatedEntityType: "project",
    },
    {
      id: "cal-3",
      title: "Offer Decision Deadline",
      description: "Deadline to respond to apartment complex offer",
      startDate: "2024-12-20T23:59:59Z",
      endDate: "2024-12-20T23:59:59Z",
      type: "offer_expiry",
      status: "upcoming",
      relatedEntityId: "offer-1",
      relatedEntityType: "offer",
    },
  ],
};

// Role-specific mock data generators
export function getMockDataByRole(role: string): Partial<DashboardData> {
  const baseData = { ...mockDashboardData };

  switch (role) {
    case "contractor":
      return {
        ...baseData,
        kpis: [
          {
            id: "total-offers",
            label: "Total Offers",
            value: 45,
            previousValue: 38,
            change: 7,
            changeType: "increase",
            format: "number",
            icon: "FileText",
            color: "blue",
          },
          {
            id: "accepted-offers",
            label: "Accepted Offers",
            value: 12,
            previousValue: 10,
            change: 2,
            changeType: "increase",
            format: "number",
            icon: "CheckCircle",
            color: "green",
          },
          {
            id: "ongoing-projects",
            label: "Ongoing Projects",
            value: 5,
            format: "number",
            icon: "Clock",
            color: "orange",
          },
          {
            id: "reputation",
            label: "Reputation Score",
            value: 4.8,
            format: "number",
            icon: "Star",
            color: "yellow",
          },
        ],
        quickActions: [
          {
            id: "browse-projects",
            label: "Browse Projects",
            description: "Find new projects to bid on",
            icon: "Search",
            url: "/dashboard/projects/browse",
            color: "blue",
            isEnabled: true,
            requiresVerification: false,
          },
          {
            id: "my-offers",
            label: "My Offers",
            description: "Track your submitted offers",
            icon: "FileText",
            url: "/dashboard/offers",
            color: "green",
            isEnabled: true,
            requiresVerification: false,
          },
        ],
      };

    case "supplier":
      return {
        ...baseData,
        kpis: [
          {
            id: "total-products",
            label: "Total Products",
            value: 156,
            previousValue: 142,
            change: 14,
            changeType: "increase",
            format: "number",
            icon: "Package",
            color: "blue",
          },
          {
            id: "pending-orders",
            label: "Pending Orders",
            value: 8,
            format: "number",
            icon: "Clock",
            color: "orange",
          },
          {
            id: "total-revenue",
            label: "Total Revenue",
            value: 245000,
            previousValue: 220000,
            change: 25000,
            changeType: "increase",
            format: "currency",
            icon: "DollarSign",
            color: "green",
          },
        ],
      };

    case "engineering_office":
      return {
        ...baseData,
        kpis: [
          {
            id: "active-projects",
            label: "Active Projects",
            value: 8,
            format: "number",
            icon: "Briefcase",
            color: "blue",
          },
          {
            id: "team-utilization",
            label: "Team Utilization",
            value: 85,
            format: "percentage",
            icon: "Users",
            color: "green",
          },
          {
            id: "completed-designs",
            label: "Completed Designs",
            value: 24,
            previousValue: 20,
            change: 4,
            changeType: "increase",
            format: "number",
            icon: "PenTool",
            color: "purple",
          },
        ],
      };

    default:
      return baseData;
  }
}
